name = "blog-posts"
main = "src/index.js"
compatibility_date = "2023-10-16"

d1_databases = [
    { binding = "DB", database_name = "tabbypage", database_id = "796eb66c-eada-4d80-a7fd-314064a04259" }
]